import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";

export const metadata: Metadata = {
	title: "Musebound",
	description: "Generated by the dark woker",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter-sans",
});

function TopNav(){ return(
	<nav className="flex items-center justify-between w-full p-4  text-xl font-semibold border-b ">
		 <div>Roleplay</div>
		 <div>Sign In</div>
	</nav>
	);
}

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
	
			<body className={`flex flex-col gap-4 font sans ${inter.variable}`}>
				<TopNav/>
				{children}
			</body>
		</html>
	);
}
