import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
import { ClerkProvider } from "@clerk/nextjs";
import {NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin"

import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import TopNav from "./_components/topnav";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";

export const metadata: Metadata = {
	title: "Musebound",
	description: "Generated by the Voor",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter-sans",
});



export default function RootLayout(props: {
	children: React.ReactNode;
	modal: React.ReactNode;
}){
	return (
		<ClerkProvider>
			<html lang="en">
				<NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
				/>
				<body className={`flex flex-col gap-4 font sans ${inter.variable}`}>
					<TopNav/>
					{props.children}
					{props.modal}
					<div id="modal-root" />
				</body>
			</html>
		</ClerkProvider>
	);
}
