import "~/styles/globals.css";
import "@uploadthing/react/styles.css";
// import { ClerkProvider } from "@clerk/nextjs";

import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import TopNav from "./_components/topnav";

export const metadata: Metadata = {
	title: "Musebound",
	description: "Generated by the Voor",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter-sans",
});



export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		// <ClerkProvider>
			<html lang="en">
				<body className={`flex flex-col gap-4 font sans ${inter.variable}`}>
					<TopNav/>
					{children}
				</body>
			</html>
		// </ClerkProvider>
	);
}
